// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_portal is a generated GoMock package.
package mock_portal

import (
	context "context"
	reflect "reflect"

	portal "github.com/MISW/portal-role-sync/infra/portal"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAllMemberRoles mocks base method.
func (m *MockClient) GetAllMemberRoles(ctx context.Context) (portal.MemberRoles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMemberRoles", ctx)
	ret0, _ := ret[0].(portal.MemberRoles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMemberRoles indicates an expected call of GetAllMemberRoles.
func (mr *MockClientMockRecorder) GetAllMemberRoles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMemberRoles", reflect.TypeOf((*MockClient)(nil).GetAllMemberRoles), ctx)
}
